name: CI

on:
  push:
    branches:
      - '**'
  release:
    types: [released, prereleased]

jobs:
  test-add:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add permissions
        run: chmod +x tests/add.sh && chmod +x AppToGrid.sh

      - name: Test Add
        working-directory: tests
        run: bash add.sh

  test-remove:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add permissions
        run: chmod +x tests/remove.sh && chmod +x AppToGrid.sh

      - name: Test Remove
        working-directory: tests
        run: bash remove.sh

  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.9.0
        env:
          SHELLCHECK_OPTS: -e SC2012
