name: CI

on:
  push:
    branches:
      - '**'
  release:
    types: [released, prereleased]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add permissions
        run: chmod +x test.sh && chmod +x AppToGrid.sh

      - name: Test
        run: test.sh
