name: CI

on:
  push:
    branches:
      - '**'
  release:
    types: [released, prereleased]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add permissions
        run: chmod +x test.sh && chmod +x AppToGrid.sh

      - name: Test
        run: bash test.sh

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.9.0
        env:
          SHELLCHECK_OPTS: -e SC2012
